name: sict-bim

services:
  python:
    build: .
    container_name: python
    tty: true
    volumes:
      - .:/root/sict-bim
  
  mongo:
    image: mongodb/mongodb-community-server:8.0.4-ubuntu2204
    container_name: mongo
    tty: true
    ports:
      - "27017:27017"